'use strict';

module.exports = {
  "1/1":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "1/2":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "1/3":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "1/4":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "1/5":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "1/6":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "1/7":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "1/8":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "1/9":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "1/10":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "1/11":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "1/12":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "1/13":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "1/14":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "1/15":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "1/16":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "1/17":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "1/18":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "1/19":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "1/20":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "1/21":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "1/22":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "1/23":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "1/24":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "1/25":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "1/26":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "1/27":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "1/28":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "1/29":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "1/30":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "1/31":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "2/1":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "2/2":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "2/3":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "2/4":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "2/5":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "2/6":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "2/7":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "2/8":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "2/9":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "2/10":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "2/11":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "2/12":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "2/13":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "2/14":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "2/15":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "2/16":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "2/17":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "2/18":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "2/19":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "2/20":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "2/21":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "2/22":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "2/23":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "2/24":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "2/25":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "2/26":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "2/27":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "2/28":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "2/29":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "3/1":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "3/2":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "3/3":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "3/4":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "3/5":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "3/6":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "3/7":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "3/8":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "3/9":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "3/10":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "3/11":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "3/12":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "3/13":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "3/14":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "3/15":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "3/16":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "3/17":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "3/18":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "3/19":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "3/20":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "3/21":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "3/22":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "3/23":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "3/24":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "3/25":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "3/26":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "3/27":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "3/28":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "3/29":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "3/30":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "3/31":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "4/1":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "4/2":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "4/3":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "4/4":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "4/5":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "4/6":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "4/7":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "4/8":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "4/9":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "4/10":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "4/11":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "4/12":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "4/13":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "4/14":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "4/15":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "4/16":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "4/17":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "4/18":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "4/19":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "4/20":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "4/21":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "4/22":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "4/23":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "4/24":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "4/25":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "4/26":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "4/27":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "4/28":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "4/29":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "4/30":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "5/1":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "5/2":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "5/3":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "5/4":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "5/5":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "5/6":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "5/7":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "5/8":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "5/9":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "5/10":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "5/11":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "5/12":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "5/13":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "5/14":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "5/15":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "5/16":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "5/17":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "5/18":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "5/19":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "5/20":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "5/21":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "5/22":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "5/23":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "5/24":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "5/25":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "5/26":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "5/27":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "5/28":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "5/29":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "5/30":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "5/31":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "6/1":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "6/2":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "6/3":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "6/4":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "6/5":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "6/6":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "6/7":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "6/8":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "6/9":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "6/10":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "6/11":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "6/12":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "6/13":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "6/14":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "6/15":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "6/16":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "6/17":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "6/18":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "6/19":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "6/20":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "6/21":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "6/22":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "6/23":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "6/24":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "6/25":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "6/26":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "6/27":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "6/28":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "6/29":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "6/30":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "7/1":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "7/2":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "7/3":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "7/4":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "7/5":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "7/6":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "7/7":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "7/8":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "7/9":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "7/10":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "7/11":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "7/12":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "7/13":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "7/14":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "7/15":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "7/16":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "7/17":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "7/18":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "7/19":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "7/20":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "7/21":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "7/22":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "7/23":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "7/24":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "7/25":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "7/26":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "7/27":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "7/28":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "7/29":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "7/30":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "7/31":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "8/1":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "8/2":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "8/3":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "8/4":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "8/5":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "8/6":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "8/7":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "8/8":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "8/9":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "8/10":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "8/11":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "8/12":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "8/13":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "8/14":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "8/15":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "8/16":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "8/17":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "8/18":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "8/19":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "8/20":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "8/21":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "8/22":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "8/23":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "8/24":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "8/25":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "8/26":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "8/27":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "8/28":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "8/29":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "8/30":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "8/31":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "9/1":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "9/2":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "9/3":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "9/4":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "9/5":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "9/6":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "9/7":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "9/8":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "9/9":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "9/10":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "9/11":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "9/12":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "9/13":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "9/14":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "9/15":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "9/16":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "9/17":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "9/18":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "9/19":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "9/20":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "9/21":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "9/22":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "9/23":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "9/24":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "9/25":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "9/26":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "9/27":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "9/28":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "9/29":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "9/30":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "10/1":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "10/2":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "10/3":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "10/4":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "10/5":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "10/6":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "10/7":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "10/8":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "10/9":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "10/10":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "10/11":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "10/12":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "10/13":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "10/14":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "10/15":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "10/16":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "10/17":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "10/18":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "10/19":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "10/20":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "10/21":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "10/22":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "10/23":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "10/24":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "10/25":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "10/26":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "10/27":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "10/28":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "10/29":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "10/30":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "10/31":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "11/1":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "11/2":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "11/3":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "11/4":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "11/5":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "11/6":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "11/7":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "11/8":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "11/9":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "11/10":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "11/11":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "11/12":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "11/13":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "11/14":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "11/15":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "11/16":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "11/17":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "11/18":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "11/19":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "11/20":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "11/21":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "11/22":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "11/23":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "11/24":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "11/25":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "11/26":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
  "11/27":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Chickpea Shawarma Salad. For Dinner: Spiced Vegan Lentil Soup",
  "11/28":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Half an avocado filled with tuna salad. For Dinner: Tuscan Chicken Skillet",
  "11/29":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Garlic Mushroom Kebabs. For Dinner: Chili made with ground Turkey, kidney beans and cayenne",
  "11/30":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Avocado Egg Salad. For Dinner: Kale and Feta One-Pot Linguine",
  "12/1":"For Breakfast: Vegetable Omelet with Asparagus, Spinach and Tomato. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Jerk Shrimp with Pineapple Rice",
  "12/2":"For Breakfast: Mediterranean Poached Eggs with whole wheat toast and sundried tomatoes. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: One-Pot Greek Oregano Chicken and Orzo with Tomatoes in Garlic Oil",
  "12/3":"For Breakfast: Oatmeal with fresh fruit and chopped almonds. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Pan seared trout seasoned with Lemon and dill, with half a cup of Quinoa",
  "12/4":"For Breakfast: Greek Yoghurt with chopped Raspberries and a splash of Maple Syrup. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Mediterranean Quinoa Bowls with Roasted Red Pepper Sauce",
  "12/5":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: One-Pan Mediterranean Cod with Cherry Tomatoes",
  "12/6":"For Breakfast: Oatmeal with Blueberries and chopped Walnuts. For Lunch: Greek Salad with Avocado. For Dinner: Five-Ingredient Lemon Chicken and Asparagus",
  "12/7":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "12/8":"For Breakfast: Omelet with Cheese, Tomato and Onion. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Kale, Cannellini and Farro Stew",
  "12/9":"For Breakfast: Poached Eggs, Potatoes and Avocado. For Lunch: Greek Kale Quinoa Salad. For Dinner: Bruschetta Chicken with Whole Grain Rice",
  "12/10":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Spinach and Bell Pepper Salad with Grilled Salmon. For Dinner: Grilled Chicken and Grape skewers.",
  "12/11":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Caprese-Style Portobello Mushrooms with Mozzerella and Tomato",
  "12/12":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Minestrone soup with sprinkle of Parmesan cheese. For Dinner: Crispy Salmon Greek Orzo",
  "12/13":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Half an avocado filled with tuna salad. For Dinner: Mediterranean Baked Sweet Potatoes with Chickpeas",
  "12/14":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Slow Cooker Mediterranean Beef Stew with Rosemary and Balsamic Vinegar",
  "12/15":"For Breakfast: Zucchini and Tomato Frittata. For Lunch: Cleansing Tabbouleh Salad: Roasted Chickpea Gyros",
  "12/16":"For Breakfast: Avocado, Egg and Spinach open-faced breakfast sandwich. For Lunch: Romaine Lettuce salad with cannelini beans, carrots and asparagus. For Dinner: Mediterranean Chicken Pasta with Spinach, Feta and Sun Dried Tomatoes",
  "12/17":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Chickpea Shawarma Salad. For Dinner: Scallops sauteed with Mushrooms and Leeks",
  "12/18":"For Breakfast: Greek Yoghurt with chopped Apples and a splash of Maple Syrup. For Lunch: Avocado Egg Salad. For Dinner: Quinoa Stuffed Eggplant with Tahini Sauce",
  "12/19":"For Breakfast: Two slices of whole grain toast with almond butter and half a pear. For Lunch: Garlic Mushroom Kebabs. For Dinner: Homemade Turkey Burgers with Avocado and Garlic Green Beans",
  "12/20":"For Breakfast: Oatmeal with Blackberries and chopped Pistachio. For Lunch: Greek Salad with Avocado. For Dinner: Shrimp Linguine with Cherry Tomatoes, Lemon and Parmesan cheese",
  "12/21":"For Breakfast: Homemade Granola with Greek Yoghurt and Blueberries. For Lunch: Spinach and Bell Pepper Salad with Grilled SalmonTuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Farro Bowl with Shiitake Mushrooms and Winter Greens",
  "12/22":"For Breakfast: Vegetable Omelet with Spinach, Mushrooms and Broccoli. For Lunch: Quinoa and Vegetable-Stuffed Portobello Mushrooms. For Dinner: Chicken Gyros & Tzatziki Sauce",
  "12/23":"For Breakfast: Scrambled Egg with Spinach and Cherry Tomatoes. For Lunch: Vegan Avocado Caprese Pasta Salad. For Dinner: Cream of Roasted Cauliflower Soup with Paprika, Cumin & Fresh Dill",
  "12/24":"For Breakfast: Greek Yoghurt with Blueberries and chopped walnuts. For Lunch: Tuna Salad with a Dijon Mustard Vinaigrette. For Dinner: Baked Sesame-Ginger Salmon in Parchment",
  "12/25":"For Breakfast: Oatmeal with chopped Strawberries and a splash of Maple Syrup. For Lunch: Spinach and bell pepper salad with leftover Salmon. For Dinner: Chickpea Vegetable Coconut Curry",
  "12/26":"For Breakfast: Two slices of whole grain toast with almond butter and half a grapefruit. For Lunch: Lentil soup with whole wheat crackers. For Dinner: Grilled Chicken + Dill Greek Yogurt Sauce",
  "12/27":"For Breakfast: Greek Yoghurt with Pomegranate Seeds and Sliced Almonds. For Lunch: Greek Kale Quinoa Salad. For Dinner: Mussels cooked in a Tomato, Garlic and Wine broth",
  "12/28":"For Breakfast: Egg White Scramble with Spinach and Cherry Tomatoes. For Lunch: Hummus with celery, bell pepper and carrots with whole wheat pita. For Dinner: Kale, Cannellini and Farro Stew",
  "12/29":"For Breakfast: Frittata with Red Pepper, Scallion and Parmesan Cheese. For Lunch: Cleansing Tabbouleh Salad. For Dinner: Greek Turkey Meatball Gyros with Tzatziki",
  "12/30":"For Breakfast: Avocado Egg and Spinach open faced breakfast sandwich. For Lunch: Cucumber Rollups with Hummus, Feta and Tomato. For Dinner: Healthy Baked Salmon Tacos",
  "12/31":"For Breakfast: Oatmeal with Blueberries and chopped walnuts. For Lunch: Homemade turkey burger with side salad or baked sweet potato fries. For Dinner: Greek Shrimp Farro Bowls",
}
